name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest  # Wymaga act_runner z etykietą ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Gitea Container Registry - ustaw GITEA_URL w secrets lub zmiennych
      # Przykład: https://gitea.example.com
      - name: Log in to Gitea Container Registry
        run: |
          echo "${{ secrets.GITEA_TOKEN }}" | docker login ${{ vars.GITEA_URL }} -u ${{ gitea.actor }} --password-stdin

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile \
            -t ${{ vars.GITEA_URL }}/${{ gitea.repository }}:${{ steps.version.outputs.VERSION }} \
            -t ${{ vars.GITEA_URL }}/${{ gitea.repository }}:latest \
            .

      - name: Push Docker image
        run: |
          docker push ${{ vars.GITEA_URL }}/${{ gitea.repository }}:${{ steps.version.outputs.VERSION }}
          docker push ${{ vars.GITEA_URL }}/${{ gitea.repository }}:latest

      - name: Create Release Notes
        run: |
          echo "## Docker Image" > release_notes.md
          echo '```bash' >> release_notes.md
          echo "docker pull ${{ vars.GITEA_URL }}/${{ gitea.repository }}:${{ steps.version.outputs.VERSION }}" >> release_notes.md
          echo '```' >> release_notes.md

      # Gitea Release - używa API
      - name: Create Gitea Release
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "tag_name": "${{ github.ref_name }}",
              "name": "Release ${{ github.ref_name }}",
              "body": "## Docker Image\n```bash\ndocker pull ${{ vars.GITEA_URL }}/${{ gitea.repository }}:${{ steps.version.outputs.VERSION }}\n```",
              "draft": false,
              "prerelease": false
            }' \
            "${{ vars.GITEA_URL }}/api/v1/repos/${{ gitea.repository }}/releases"
